# Generated by Django 4.1.3 on 2022-11-20 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accomplishments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('Uploads', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=100)),
                ('Region', models.CharField(max_length=100)),
                ('Street', models.CharField(max_length=100)),
                ('PostalCode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('Date', models.DateTimeField(auto_now=True)),
                ('Uploads', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='DLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('StartDate', models.DateTimeField(auto_now=True)),
                ('EndDate', models.DateTimeField(auto_now=True)),
                ('Uploads', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContactInfo', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('JobTitle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VCS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('StartDate', models.DateTimeField(auto_now=True)),
                ('EndDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='accomplishments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_api.accomplishments'),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='portfolio_api.address'),
        ),
        migrations.AddField(
            model_name='user',
            name='ah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_api.ah'),
        ),
        migrations.AddField(
            model_name='user',
            name='dlc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_api.dlc'),
        ),
        migrations.AddField(
            model_name='user',
            name='references',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_api.references'),
        ),
        migrations.AddField(
            model_name='user',
            name='vcs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_api.vcs'),
        ),
    ]
