# Generated by Django 4.1.3 on 2022-11-24 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0002_accomplishments_address_ah_dlc_references_vcs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accomplishments',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='accomplishments',
            old_name='Type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='accomplishments',
            old_name='Uploads',
            new_name='uploads',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='PostalCode',
            new_name='postalCode',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='Region',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='Street',
            new_name='street',
        ),
        migrations.RenameField(
            model_name='ah',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='ah',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='ah',
            old_name='Type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='ah',
            old_name='Uploads',
            new_name='uploads',
        ),
        migrations.RenameField(
            model_name='dlc',
            old_name='EndDate',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='dlc',
            old_name='StartDate',
            new_name='startDate',
        ),
        migrations.RenameField(
            model_name='dlc',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='dlc',
            old_name='Type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='dlc',
            old_name='Uploads',
            new_name='uploads',
        ),
        migrations.RenameField(
            model_name='references',
            old_name='ContactInfo',
            new_name='contactInfo',
        ),
        migrations.RenameField(
            model_name='references',
            old_name='JobTitle',
            new_name='jobTitle',
        ),
        migrations.RenameField(
            model_name='references',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='vcs',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='vcs',
            old_name='StartDate',
            new_name='startDate',
        ),
        migrations.RenameField(
            model_name='vcs',
            old_name='Title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='user',
            name='accomplishments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_api.accomplishments'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_api.ah'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dlc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_api.dlc'),
        ),
        migrations.AlterField(
            model_name='user',
            name='references',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_api.references'),
        ),
        migrations.AlterField(
            model_name='user',
            name='vcs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_api.vcs'),
        ),
    ]
