# Generated by Django 4.1.3 on 2022-11-24 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0003_rename_title_accomplishments_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vcs',
            old_name='EndDate',
            new_name='endDate',
        ),
        migrations.AlterField(
            model_name='user',
            name='accomplishments',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='portfolio_api.accomplishments'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ah',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='portfolio_api.ah'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dlc',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='portfolio_api.dlc'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='references',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='portfolio_api.references'),
        ),
        migrations.AlterField(
            model_name='user',
            name='vcs',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='portfolio_api.vcs'),
        ),
    ]
